#!/bin/bash
#SBATCH --qos=high
#SBATCH --job-name=pvpost
#SBATCH --partition=standard
#SBATCH --nodes=1
#SBATCH --time=12:00:00
#SBATCH --account=bpms
#SBATCH --output=pv_post_log.out

module purge
module load openmpi/1.10.7/gcc-7.3.0
module load gcc
#module load paraview # load an older version of paraview to avoid threshold change error
module load paraview/5.6.0 # load an older version of paraview to avoid threshold change error
source /projects/bpms/openfoam/OpenFOAM-dev/etc/bashrc # point to the openfoam in ethan's dir
rm -rf 0.0/
rm -rf 0/
reconstructPar -withZero -newTimes
mv 0/ 0.0/
pvpython pv_extract_analyze_script.py 
pvpython pv_extract_our.py 100.0 0.01

