#!/bin/bash
#SBATCH --job-name=bcolumn
#SBATCH --partition=short
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=36
#SBATCH --time=04:00:00
#SBATCH --account=vebio
#SBATCH --output=log.out

module purge
module load openmpi/4.1.0/gcc-8.4.0 
module load gcc
source /projects/vebio/eyoung/VirtualEngineering/submodules/OpenFOAM-dev/etc/bashrc

. ./presteps.sh
srun -n 72 reactingTwoPhaseEulerFoam -parallel

# Run the post-processing script
module load paraview/5.6.0
rm -rf 0.0/
rm -rf 0/
reconstructPar -latestTime
mv 0/ 0.0/
pvpython pv_extract_analyze_script.py 