#!/bin/bash
#SBATCH --job-name=bcolumn
#SBATCH --partition=short
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=36
#SBATCH --time=04:00:00
#SBATCH --account=vebio
#SBATCH --output=log.out

module purge
module load openmpi/1.10.7/gcc-7.3.0
module load gcc
source /projects/vebio/hsitaram/VirtualEngineering/submodules/OpenFOAM-dev/etc/bashrc
. ./presteps.sh
srun -n 72 reactingTwoPhaseEulerFoam -parallel
