# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_vebio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test_vebio - ${{ matrix.os }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
        os:
          - linux
          - macos
        include:
          - os: linux
            os-version: ubuntu-20.04
          - os: macos
            os-version: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install Virtual Engineering Conda environment
      shell: pwsh
      run: |
        conda env create -f environment.yaml -n test-env
        conda activate test-env
        conda list
    - name: Compile PT library and module
      shell: pwsh
      run: |
        conda activate test-env
        make -C pretreatment_model/bld/ ptpython
        cp pretreatment_model/bld/*.so pretreatment_model/test/
        sudo cp pretreatment_model/bld/*.so /lib/
        sudo cp pretreatment_model/bld/*.so /usr/local/lib/
    - name: Test Virtual Engineering functions with pytest
      shell: pwsh
      run: |
        conda activate test-env
        pytest -s vebio/tests/
